from state import AgentState
from services.llm_service import generate
from services.prompt_manager import load_prompt


def critic_agent(state: AgentState) -> AgentState:
    """
    Critic Agent

    Evaluates and improves the innovation
    opportunities generated by the Innovation Agent.
    """

    prompt = load_prompt(
        "critic",
        topic=state["topic"],
        gaps=state["gaps"],
        innovation=state["innovation"]
    )

    response = generate(prompt)

    state["critique"] = response

    return state